/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.dsmailand.abirechner.gui;

import it.dsmailand.abirechner.data.Data;
import it.dsmailand.abirechner.subjects.Subject;
import java.util.NoSuchElementException;
import javax.swing.JComboBox;

/**
 *
 * @author Luca13
 */
public class ChoicePanel extends javax.swing.JPanel {

    private JComboBox[] boxes = new JComboBox[4];
    /**
     * Creates new form ChoicePanel
     */
    public ChoicePanel() {
        initComponents();
        boxes[0]=jComboBox1;
        boxes[1]=jComboBox2;
        boxes[2]=jComboBox3;
        boxes[3]=jComboBox4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();

        jLabel1.setText("Wahl der Prüfungsfächer");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deutsch" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mathematik", "Italienisch", "Englisch", "Französisch", "Latein", "Physik", "Chemie", "Biologie", "Geschichte" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mathematik", "Italienisch", "Englisch", "Französisch", "Latein", "Physik", "Chemie", "Biologie", "Geschichte" }));
        jComboBox3.setSelectedIndex(1);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mathematik", "Italienisch", "Englisch", "Französisch", "Latein", "Physik", "Chemie", "Biologie", "Geschichte", "Filosofia", "Sport", "Kunst/Musik", "PoWi", "Religion/Ethik" }));
        jComboBox4.setSelectedIndex(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void readInputToData(Data data) {
        data.resetChoices();
        for(int i = 0; i<4; i++)    {
            JComboBox thisBox = boxes[i];
            String selectedSubject = (String) thisBox.getSelectedItem();
            try{
                Subject thisSubject = data.findSubject(selectedSubject);
                if(i<3) {
                    thisSubject.writtenExamSubject = true;
                } else {
                    thisSubject.oralExamSubject = true;
                }
            }
            catch(NoSuchElementException e) {
                System.err.println("NoSuchElementException: Subject \"" + selectedSubject + "\" not found.");
            }
        }
    }
}
