/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.dsmailand.abirechner.gui;

/**
 *
 * @author Luca13
 */
public class OutputPanel extends javax.swing.JPanel {

    /**
     * Creates new form OutputPanel
     */
    public OutputPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        finalMarkLabel = new javax.swing.JLabel();
        nextMarkPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nextBetterLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nextWorseLabel = new javax.swing.JLabel();

        jLabel1.setText("Punkte:");

        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scoreLabel.setText("###");

        jLabel3.setText("Abiturnote:");

        finalMarkLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalMarkLabel.setText("###");

        jLabel5.setText("Punkte zur nächsten besseren Note:");

        nextBetterLabel.setText("###");

        jLabel7.setText("Punkte zur nächsten schlechteren Note:");

        nextWorseLabel.setText("###");

        javax.swing.GroupLayout nextMarkPanelLayout = new javax.swing.GroupLayout(nextMarkPanel);
        nextMarkPanel.setLayout(nextMarkPanelLayout);
        nextMarkPanelLayout.setHorizontalGroup(
            nextMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextMarkPanelLayout.createSequentialGroup()
                .addGroup(nextMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(nextBetterLabel)
                    .addComponent(jLabel7)
                    .addComponent(nextWorseLabel))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        nextMarkPanelLayout.setVerticalGroup(
            nextMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextMarkPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextBetterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextWorseLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextMarkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(scoreLabel)
                            .addComponent(jLabel3)
                            .addComponent(finalMarkLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalMarkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextMarkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalMarkLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nextBetterLabel;
    private javax.swing.JPanel nextMarkPanel;
    private javax.swing.JLabel nextWorseLabel;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
