/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.dsmailand.abirechner.gui;

/**
 *
 * @author Carl
 */
public class UserInputPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserInputPanel
     */
    public UserInputPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sDeutschLabel = new javax.swing.JLabel();
        semesterLabel0 = new javax.swing.JLabel();
        semesterLabel1 = new javax.swing.JLabel();
        semesterLabel2 = new javax.swing.JLabel();
        semesterLabel3 = new javax.swing.JLabel();
        sItaLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        markTextField5 = new javax.swing.JTextField();
        markTextField6 = new javax.swing.JTextField();
        markTextField7 = new javax.swing.JTextField();
        markTextField8 = new javax.swing.JTextField();
        markTextField9 = new javax.swing.JTextField();
        markTextField10 = new javax.swing.JTextField();
        markTextField11 = new javax.swing.JTextField();
        markTextField12 = new javax.swing.JTextField();
        markTextField13 = new javax.swing.JTextField();
        markTextField14 = new javax.swing.JTextField();
        markTextField15 = new javax.swing.JTextField();
        markTextField16 = new javax.swing.JTextField();
        markTextField17 = new javax.swing.JTextField();
        markTextField18 = new javax.swing.JTextField();
        markTextField19 = new javax.swing.JTextField();
        markTextField20 = new javax.swing.JTextField();
        markTextField21 = new javax.swing.JTextField();
        markTextField22 = new javax.swing.JTextField();
        markTextField23 = new javax.swing.JTextField();
        markTextField24 = new javax.swing.JTextField();
        markTextField25 = new javax.swing.JTextField();
        markTextField26 = new javax.swing.JTextField();
        markTextField27 = new javax.swing.JTextField();
        markTextField28 = new javax.swing.JTextField();
        markTextField29 = new javax.swing.JTextField();
        markTextField30 = new javax.swing.JTextField();
        markTextField31 = new javax.swing.JTextField();
        markTextField32 = new javax.swing.JTextField();
        markTextField33 = new javax.swing.JTextField();
        markTextField34 = new javax.swing.JTextField();
        markTextField35 = new javax.swing.JTextField();
        markTextField36 = new javax.swing.JTextField();
        markTextField37 = new javax.swing.JTextField();
        markTextField38 = new javax.swing.JTextField();
        markTextField39 = new javax.swing.JTextField();
        markTextField40 = new javax.swing.JTextField();
        markTextField41 = new javax.swing.JTextField();
        markTextField42 = new javax.swing.JTextField();
        markTextField43 = new javax.swing.JTextField();
        markTextField44 = new javax.swing.JTextField();
        markTextField45 = new javax.swing.JTextField();
        markTextField46 = new javax.swing.JTextField();
        markTextField47 = new javax.swing.JTextField();
        markTextField48 = new javax.swing.JTextField();
        markTextField49 = new javax.swing.JTextField();
        markTextField50 = new javax.swing.JTextField();
        markTextField51 = new javax.swing.JTextField();
        markTextField52 = new javax.swing.JTextField();
        sMatheLabel = new javax.swing.JLabel();
        sGeschichteLabel = new javax.swing.JLabel();
        sFilosofiaLabel = new javax.swing.JLabel();
        sSportLabel = new javax.swing.JLabel();
        sKunstMusikComboBox = new javax.swing.JComboBox();
        sPoWiComboBox = new javax.swing.JComboBox();
        sReligionEthikComboBox = new javax.swing.JComboBox();

        sDeutschLabel.setText("Deutsch");

        semesterLabel0.setText("12.1");

        semesterLabel1.setText("12.2");

        semesterLabel2.setText("13.1");

        semesterLabel3.setText("13.2");

        sItaLabel.setText("Italienisch");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        markTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField5ActionPerformed(evt);
            }
        });

        markTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField6ActionPerformed(evt);
            }
        });

        markTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField7ActionPerformed(evt);
            }
        });

        markTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField8ActionPerformed(evt);
            }
        });

        markTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField9ActionPerformed(evt);
            }
        });

        markTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField10ActionPerformed(evt);
            }
        });

        markTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField11ActionPerformed(evt);
            }
        });

        markTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField12ActionPerformed(evt);
            }
        });

        markTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField13ActionPerformed(evt);
            }
        });

        markTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField14ActionPerformed(evt);
            }
        });

        markTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField15ActionPerformed(evt);
            }
        });

        markTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField16ActionPerformed(evt);
            }
        });

        markTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField17ActionPerformed(evt);
            }
        });

        markTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField18ActionPerformed(evt);
            }
        });

        markTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField19ActionPerformed(evt);
            }
        });

        markTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField20ActionPerformed(evt);
            }
        });

        markTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField21ActionPerformed(evt);
            }
        });

        markTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField22ActionPerformed(evt);
            }
        });

        markTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField23ActionPerformed(evt);
            }
        });

        markTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField24ActionPerformed(evt);
            }
        });

        markTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField25ActionPerformed(evt);
            }
        });

        markTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField26ActionPerformed(evt);
            }
        });

        markTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField27ActionPerformed(evt);
            }
        });

        markTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField28ActionPerformed(evt);
            }
        });

        markTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField29ActionPerformed(evt);
            }
        });

        markTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField30ActionPerformed(evt);
            }
        });

        markTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField31ActionPerformed(evt);
            }
        });

        markTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField32ActionPerformed(evt);
            }
        });

        markTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField33ActionPerformed(evt);
            }
        });

        markTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField34ActionPerformed(evt);
            }
        });

        markTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField35ActionPerformed(evt);
            }
        });

        markTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField36ActionPerformed(evt);
            }
        });

        markTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField37ActionPerformed(evt);
            }
        });

        markTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField38ActionPerformed(evt);
            }
        });

        markTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField39ActionPerformed(evt);
            }
        });

        markTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField40ActionPerformed(evt);
            }
        });

        markTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField41ActionPerformed(evt);
            }
        });

        markTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField42ActionPerformed(evt);
            }
        });

        markTextField43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField43ActionPerformed(evt);
            }
        });

        markTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField44ActionPerformed(evt);
            }
        });

        markTextField45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField45ActionPerformed(evt);
            }
        });

        markTextField46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField46ActionPerformed(evt);
            }
        });

        markTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField47ActionPerformed(evt);
            }
        });

        markTextField48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField48ActionPerformed(evt);
            }
        });

        markTextField49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField49ActionPerformed(evt);
            }
        });

        markTextField50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField50ActionPerformed(evt);
            }
        });

        markTextField51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField51ActionPerformed(evt);
            }
        });

        markTextField52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextField52ActionPerformed(evt);
            }
        });

        sMatheLabel.setText("Mathematik");

        sGeschichteLabel.setText("Geschichte");

        sFilosofiaLabel.setText("Filosofia");

        sSportLabel.setText("Sport");

        sKunstMusikComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kunst", "Musik" }));

        sPoWiComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PoWi bilingual", "PoWi deutsch" }));

        sReligionEthikComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Religion", "Ethik" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sDeutschLabel)
                    .addComponent(sItaLabel)
                    .addComponent(sMatheLabel)
                    .addComponent(sGeschichteLabel)
                    .addComponent(sFilosofiaLabel)
                    .addComponent(sSportLabel)
                    .addComponent(sKunstMusikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPoWiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sReligionEthikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(semesterLabel0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(semesterLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(semesterLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(semesterLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterLabel0)
                    .addComponent(semesterLabel1)
                    .addComponent(semesterLabel2)
                    .addComponent(semesterLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sDeutschLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(markTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(markTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(markTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(markTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sItaLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(markTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(markTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(markTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(markTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(markTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(markTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sMatheLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sGeschichteLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sFilosofiaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sSportLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sKunstMusikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sPoWiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sReligionEthikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void markTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField5ActionPerformed

    private void markTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField6ActionPerformed

    private void markTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField7ActionPerformed

    private void markTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField8ActionPerformed

    private void markTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField9ActionPerformed

    private void markTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField10ActionPerformed

    private void markTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField11ActionPerformed

    private void markTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField12ActionPerformed

    private void markTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField13ActionPerformed

    private void markTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField14ActionPerformed

    private void markTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField15ActionPerformed

    private void markTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField16ActionPerformed

    private void markTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField17ActionPerformed

    private void markTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField18ActionPerformed

    private void markTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField19ActionPerformed

    private void markTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField20ActionPerformed

    private void markTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField21ActionPerformed

    private void markTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField22ActionPerformed

    private void markTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField23ActionPerformed

    private void markTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField24ActionPerformed

    private void markTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField25ActionPerformed

    private void markTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField26ActionPerformed

    private void markTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField27ActionPerformed

    private void markTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField28ActionPerformed

    private void markTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField29ActionPerformed

    private void markTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField30ActionPerformed

    private void markTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField31ActionPerformed

    private void markTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField32ActionPerformed

    private void markTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField33ActionPerformed

    private void markTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField34ActionPerformed

    private void markTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField35ActionPerformed

    private void markTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField36ActionPerformed

    private void markTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField37ActionPerformed

    private void markTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField38ActionPerformed

    private void markTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField39ActionPerformed

    private void markTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField40ActionPerformed

    private void markTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField41ActionPerformed

    private void markTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField42ActionPerformed

    private void markTextField43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField43ActionPerformed

    private void markTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField44ActionPerformed

    private void markTextField45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField45ActionPerformed

    private void markTextField46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField46ActionPerformed

    private void markTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField47ActionPerformed

    private void markTextField48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField48ActionPerformed

    private void markTextField49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField49ActionPerformed

    private void markTextField50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField50ActionPerformed

    private void markTextField51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField51ActionPerformed

    private void markTextField52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextField52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markTextField52ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField markTextField10;
    private javax.swing.JTextField markTextField11;
    private javax.swing.JTextField markTextField12;
    private javax.swing.JTextField markTextField13;
    private javax.swing.JTextField markTextField14;
    private javax.swing.JTextField markTextField15;
    private javax.swing.JTextField markTextField16;
    private javax.swing.JTextField markTextField17;
    private javax.swing.JTextField markTextField18;
    private javax.swing.JTextField markTextField19;
    private javax.swing.JTextField markTextField20;
    private javax.swing.JTextField markTextField21;
    private javax.swing.JTextField markTextField22;
    private javax.swing.JTextField markTextField23;
    private javax.swing.JTextField markTextField24;
    private javax.swing.JTextField markTextField25;
    private javax.swing.JTextField markTextField26;
    private javax.swing.JTextField markTextField27;
    private javax.swing.JTextField markTextField28;
    private javax.swing.JTextField markTextField29;
    private javax.swing.JTextField markTextField30;
    private javax.swing.JTextField markTextField31;
    private javax.swing.JTextField markTextField32;
    private javax.swing.JTextField markTextField33;
    private javax.swing.JTextField markTextField34;
    private javax.swing.JTextField markTextField35;
    private javax.swing.JTextField markTextField36;
    private javax.swing.JTextField markTextField37;
    private javax.swing.JTextField markTextField38;
    private javax.swing.JTextField markTextField39;
    private javax.swing.JTextField markTextField40;
    private javax.swing.JTextField markTextField41;
    private javax.swing.JTextField markTextField42;
    private javax.swing.JTextField markTextField43;
    private javax.swing.JTextField markTextField44;
    private javax.swing.JTextField markTextField45;
    private javax.swing.JTextField markTextField46;
    private javax.swing.JTextField markTextField47;
    private javax.swing.JTextField markTextField48;
    private javax.swing.JTextField markTextField49;
    private javax.swing.JTextField markTextField5;
    private javax.swing.JTextField markTextField50;
    private javax.swing.JTextField markTextField51;
    private javax.swing.JTextField markTextField52;
    private javax.swing.JTextField markTextField6;
    private javax.swing.JTextField markTextField7;
    private javax.swing.JTextField markTextField8;
    private javax.swing.JTextField markTextField9;
    private javax.swing.JLabel sDeutschLabel;
    private javax.swing.JLabel sFilosofiaLabel;
    private javax.swing.JLabel sGeschichteLabel;
    private javax.swing.JLabel sItaLabel;
    private javax.swing.JComboBox sKunstMusikComboBox;
    private javax.swing.JLabel sMatheLabel;
    private javax.swing.JComboBox sPoWiComboBox;
    private javax.swing.JComboBox sReligionEthikComboBox;
    private javax.swing.JLabel sSportLabel;
    private javax.swing.JLabel semesterLabel0;
    private javax.swing.JLabel semesterLabel1;
    private javax.swing.JLabel semesterLabel2;
    private javax.swing.JLabel semesterLabel3;
    // End of variables declaration//GEN-END:variables
}
